### PR TITLE
cmd/7a: recognize register g, and not R29.

### LINKED ISSUE #35: runtime: no definition of g on arm64
`/home/dfc/go.arm64/src/runtime/asm_arm64.s:15 syntax error, last name: g`

Did we ever sort out which register we were going to devote to `g`?

### PR DESCRIPTION
**Pull request by minux**
It brings the assembler in line with 5a and 9a.

Fixes #35.

### CODE REVIEW

**Comment by davecheney** [comment]
Nice. I have a memory we did this for 5g (and I guess 9g)

**Comment by davecheney** [comment]
Ops, sorry aram, now you have a merge commit not a cherry pick. My bad.

**Comment by minux** [comment]
Let's force update dev.arm64 branch and remove the merge commit
before it's too late.

**Comment by davecheney** [comment]
If you know how to do that go for it, i'm a git noob

**Comment by minux** [comment]
Done.

**Pull request merged**
