### PR TITLE
cmd/7g: fix floating OMINUS

### PR DESCRIPTION
**Pull request by mwhudson**
restore code dave removed when fixing OMINUS for integers...

fixes compilation of -x where x is a float

### CODE REVIEW

**Comment by davecheney** [comment]
LGTM. Please merge it how aram likes

**Comment by minux** [comment]
Why use OMUL when FNEG is available?

**Comment by mwhudson** [comment]
Just taking the path of least resistance.

**Comment by minux** [comment]
Why is using FNEG more complicated? liblink supports both FNEGS and FNEGD.

I think
https://github.com/minux/go.arm64/commit/eb0f62f60966531a1dae346ff22e04bd36fb3bab
is the correct fix.

(cmd/9g is wrong too, my bad.)

**Comment by minux** [comment]
Sorry, I forgot it's a private repo. I will send a pull request.

**Comment by minux** [comment]
Update: Power doesn't have FNEGS, only FNEG. That's the reason it
is using OMUL -1 for floating point.

**Comment by mwhudson** [comment]
This is getting waaaaaay off topic, but I think on POWER you can use FNEG on single precision values...  lfs converts a float32 to the float64 with the same value and flipping the sign bit is not going to convert a float64 that can be represented as a float32 into one that cannot...

**Comment by minux** [comment]
You're right. POWER ISA documents that FNEG simply inverts bit 0, so
it should work on both float32 and float64.

**Pull request merged**
