### PR TITLE
cmd/gc: support checknil on non-reg operands on arm64

### PR DESCRIPTION
**Pull request by mwhudson**
This feels like I am continuing the perpetration of a hack but oh well.

### CODE REVIEW

**Comment by davecheney** [comment]
Thanks. Maybe it's work doing a sweep for all other uses of that condition and preemptively fix them.

fwiw, the `theChar` stuff is going to go away after the transition to Go, but no method for doing so has been proposed.

**Comment by minux** [comment]
Why would thechar go away after the transition to Go?

**Comment by davecheney** [comment]
'cos russ said he wants it to go away.

**Comment by davecheney** [comment]
I thought that he meant it would move into liblink's ctx structure. But
that is just supposition.

**Comment by minux** [comment]
On Thu, Dec 11, 2014 at 8:25 PM, Dave Cheney notifications@github.com
wrote:

> I thought that he meant it would move into liblink's ctx structure. But
> that is just supposition.

If the compilers for different architectures are still separate, then we
still
need a way to name them separately, and thechar will likely remain in
that case.

**Comment by davecheney** [comment]
I am sorry, I was not clear.

I did not mean that `theChar` would go away, just the switching on
`theChar` in the cases that this PR highlights.

**Pull request merged**
