### PR TITLE
runtime: implement memclr_arm64.s

### PR DESCRIPTION
**Pull request by mwhudson**

### CODE REVIEW

**Comment by davecheney** [comment]
LGTM. I'm wondering if we should be writing these in Go.

**Comment by minux** [comment]
I think it's possible to use Go to write these.

**Comment by davecheney** [comment]
Given Michael has done the work,there is no point in throwing this away, but it sounds reasonable to write anything else in Go.

**Comment by minux** [comment]
I agree. We need to write these in assembler for performance reasons anyway.

**Comment by davecheney** [comment]
Of course, the final impl should be in asm, but to get things going (tm)
.go is probably fine.

-- however, given the stub for these functions is defined in stubs.go, it
makes it hard to replace that with a full impl without going down the route
of splitting that file up.

**Comment by minux** [comment]
On Mon, Jan 12, 2015 at 10:55 PM, Dave Cheney notifications@github.com
wrote:

> -- however, given the stub for these functions is defined in stubs.go, it
> makes it hard to replace that with a full impl without going down the
> route
> of splitting that file up.
> 
> Actually, there is a trick of writing the function in Go without splitting the
> declaration file.

in runtime/memclr_arm64.go, write:
package runtime

import "unsafe"

//go:linkname memclr runtime.memclrgo

func memclrgo(ptr unsafe.Pointer, n uintptr) {
    // implement it
}

No need to change any other files.

Please don't spread it, it's too tricky and should be limited to very low-level
use of Go (I recently used this trick to fix SWIG for 1.5 while maintaining
compatibility with earlier Go versions, which use 6c to compile wrappers.)

**Comment by davecheney** [comment]
Thanks for the tip

**Comment by 4ad** [comment]
Merged.

**Comment by mwhudson** [comment]
It would be interesting to try to write these in Go.  I don't think it's completely obvious that the assembly one would be much faster (I'm certain I can write a faster memmove in go that the byte-by-byte assembly one I submitted :-p)

**Comment by davecheney** [comment]
I realise that this is getting off topic, but I was thinking about the arm
eqstring and memeq. I think they could be written in Go and produce almost
the same assembly output (the trick is you need to type assert the starting
pointer to a [1<<32/64]byte) and adjust your index appropriately, but that
should eliminate all the bounds checking.

**Comment by minux** [comment]
On Tue, Jan 13, 2015 at 4:03 PM, Dave Cheney notifications@github.com
wrote:

> I realise that this is getting off topic, but I was thinking about the arm
> eqstring and memeq. I think they could be written in Go and produce almost
> the same assembly output (the trick is you need to type assert the
> starting
> pointer to a [1<<32/64]byte) and adjust your index appropriately, but that
> should eliminate all the bounds checking.
> 
> I think using pointer arithmetic will also remove all the bounds checking.

For example, this one doesn't even have nilchecks on amd64.
diff --git a/src/runtime/memclr_amd64.s b/src/runtime/memclr_amd64.s
index ec24f1d..8966419 100644
--- a/src/runtime/memclr_amd64.s
+++ b/src/runtime/memclr_amd64.s
@@ -3,6 +3,7 @@
 // license that can be found in the LICENSE file.

 // +build !plan9
+// +build !linux

 #include "textflag.h"

diff --git a/src/runtime/stubs_amd64.go b/src/runtime/stubs_amd64.go
new file mode 100644
index 0000000..70b6c0e
--- /dev/null
+++ b/src/runtime/stubs_amd64.go
@@ -0,0 +1,13 @@
+package runtime
+
+import "unsafe"
+
+//go:linkname memclr runtime.memclr
+//go:linkname memclrgo runtime.memclr
+
+//go:nosplit
+func memclrgo(ptr unsafe.Pointer, size int) {
-       for i := 0; i < size; i++ {
-               _(_byte)(unsafe.Pointer(uintptr(ptr) + uintptr(i))) = 0
-       }
  +}

(the //go:linkname usage is even more tricky than I've expected, because
there
are assembly code that calls runtime.memclr directly.)

(It's a working patch on linux/amd64. all.bash passes.

(Of course, in real runtime code, we will use the add func in stubs.go to
simplify
the type casts.)

**Pull request closed without merging**
