### PR TITLE
runtime: add memeq

### PR DESCRIPTION
**Pull request by davecheney**
Depends on #36

### CODE REVIEW

**Comment by minux** [comment]
Similarly, we need to git cherry-pick this pull request too.

FYI, it seems if you clone a private repository, the clone will be
a private repository for you, but you don't need to upgrade to paid
github plan for this (I was surprised when I tried to clone this.)

**Comment by davecheney** [comment]
Aram takes care of the cherry picking (thankfully)

Nice tip about the private repo.

**Comment by davecheney** [comment]
PTAL

**Comment by 4ad** [comment]
Merged.

**Pull request closed without merging**
