### PR TITLE
syscall: add _linux_arm64.go

### LINKED ISSUE #50: syscall: syscall package is incomplete
```
syscall
/home/dfc/go.arm64/src/syscall/flock.go:16: undefined: Flock_t
/home/dfc/go.arm64/src/syscall/lsf_linux.go:13: undefined: SockFilter
/home/dfc/go.arm64/src/syscall/lsf_linux.go:17: undefined: SockFilter
/home/dfc/go.arm64/src/syscall/lsf_linux.go:40: undefined: IFNAMSIZ
/home/dfc/go.arm64/src/syscall/lsf_linux.go:40: invalid array bound IFNAMSIZ
```

Probably missing `{z,}linux_arm64.go`

### PR DESCRIPTION
**Pull request by davecheney**
Can't rebuild any of these files without cgo working.

Fixes #50 

zsysnum_linux_arm64.go should also be rebuilt but the machine I'm using doesn't have the headers installed, and I don't have root.

### CODE REVIEW

**Comment by minux** [comment]
I think we can use gccgo to compile a working cmd/cgo.

**Comment by davecheney** [comment]
Sadly gccgo is not installed on this system and I don't have permission to
install the prerequisites to build it locally

**Comment by minux** [comment]
On Mon, Jan 12, 2015 at 7:18 PM, Dave Cheney notifications@github.com
wrote:

> Sadly gccgo is not installed on this system and I don't have permission to
> install the prerequisites to build it locally
> 
> you mean gmp/mpfr etc.?

You don't need to install those globally, they can be built statically into
gcc along with other parts of gcc.

cd gcc-4.9.2
./contrib/download_prerequisites

mkdir build
cd build
../configure --enable-languages=go --disable-bootstrap --prefix=$HOME/gccgo
make -j4
make install

**Comment by davecheney** [comment]
I'm sorry but I cannot do that (I've tried) this machine is simply missing
the basics of a c development environment.

**Comment by minux** [comment]
On Mon, Jan 12, 2015 at 7:39 PM, Dave Cheney notifications@github.com
wrote:

> I'm sorry but I cannot do that (I've tried) this machine is simply missing
> the basics of a c development environment.

But how could you compile cmd/dist?

I guess what it lacks is a c++ environment, and in that case, you need a two
step process to get latest gccgo up and running.

first build gcc 4.7.4 with --enable-languages=c,c++, it only requires C
toolchain,
and then use that to build latest gccgo. (actually, gcc 4.7.4 contains a Go
1.0
gccgo, but I'm not sure current cmd/cgo can be built by a Go 1.0 toolchain.)

**Comment by 4ad** [comment]
I'm confused. I run cmd/cgo without any problem using the linux/arm port.

**Comment by minux** [comment]
Aha, I also forgot the fact that linux/arm is port is working on arm64.

**Comment by 4ad** [comment]
It works due to the virtue of statically compiled binaries. The distro doesn't ship with any 32-bit shared library, not even ld.so. And the library layout is such that you would not be able to copy 32-bit libraries manually because of name clashes.

But since Go generates static binaries we don't have that problem. Unfortunately, gdb sometimes gets confused, but mostly it works.

**Comment by davecheney** [comment]
PTAL. 

I have regenerated all the files natively\* with the exception of `zsysnum_linux_arm64.go` which I am still working on.
- using a modified version of cgo which understands ptrs are 8 bytes on arm64

**Comment by davecheney** [comment]
ok, all regenerated and `./mkall.sh` is correct.

**Comment by davecheney** [comment]
This is all complete and working, please merge.

**Comment by 4ad** [comment]
Merged.

**Comment by davecheney** [comment]
@4ad, thanks for merging this. Any idea what is going on with the compiler
failures?

**Pull request closed without merging**
